all:
	gcc -Iinclude/ src/draw.c  src/model.c src/raptor.c -lSOIL -lobj -lopengl32 -lglu32 -lglut32 -lm -o raptor.exe -Wall -Wextra -Wpedantic
linux:
	gcc -Iinclude/ src/draw.c  src/model.c src/raptor.c -lSOIL -lobj -lGL -lGLU -lglut -lm -o raptor -Wall -Wextra -Wpedantic

